[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs",
  "storage-proofs/core",
  "storage-proofs/porep",
  "storage-proofs/post",
  "fil-proofs-tooling",
  "sha2raw",
  "apps/sealing",
  "apps/create-label",
  "apps/merkle-tree",
  "apps/drg-parents"
]
